version: "3.9"

services:

  db:

    image: postgres

    restart: always

    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: tasks

    ports:
      - "5432:5432"

    volumes:
      - taskdata:/var/lib/postgresql

  api:

    build: .

    depends_on:
      - db

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: postgres://postgres:dev@db:5432/tasks

volumes:
  taskdata: