openapi: 3.0.0

info:
  title: Task API
  version: 1.0.0
  description: Simple CRUD API for managing tasks.

servers:
  - url: http://localhost:3000

paths:

  /:
    get:
      summary: API information
      responses:
        '200':
          description: API information returned successfully

  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: API is running

  /tasks:

    get:
      summary: Get all tasks
      responses:
        '200':
          description: Success

    post:
      summary: Create a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  example: Learn Docker

      responses:
        '201':
          description: Created

  /tasks/{id}:

    get:
      summary: Get one task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '404':
          description: Task not found

    put:
      summary: Update a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                done:
                  type: boolean

      responses:
        '200':
          description: Updated
        '404':
          description: Task not found

    delete:
      summary: Delete a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      responses:
        '204':
          description: Deleted
        '404':
          description: Task not found